---
- name: Update APT cache
  apt: update_cache=yes
  sudo: yes
  ignore_errors: yes

- name: Check if 'curl' is on the PATH
  shell: which curl
  sudo: yes
  ignore_errors: yes
  register: which_curl_cmd

- name: Install package 'curl'
  apt: pkg=curl state=present
  register: curl_install
  when: which_curl_cmd.rc != 0
  sudo: yes
