---
- name: Update APT cache
  apt:
    update_cache: yes
  ignore_errors: yes
  sudo: yes

- name: Check if 'curl' is on the PATH
  shell: which curl
  register: which_curl_cmd
  ignore_errors: yes
  sudo: yes

- name: Install package 'curl'
  apt:
    pkg: curl
    state: present
  register: curl_install
  when: which_curl_cmd.rc != 0
  sudo: yes
